project:
  type: book

book:
  title: "Modelos lineales 1"
  author: "Lucio Cornejo"
  date: "2025/03/24"
  chapters:
    - index.qmd
    - part: "Semana 1"
      chapters: 
        - apuntes/clase-01.qmd
    - part: "Semana 2"
      chapters: 
        - apuntes/clase-02.qmd
    - part: "Semana 3"
      chapters: 
        - apuntes/clase-03.qmd
        - apuntes/clase-04.qmd
    - part: "Semana 4"
      chapters: 
        - apuntes/clase-05.qmd

    - part: "Semana 8"
      chapters: 
        - apuntes/clase-08.qmd

    - part: "Semana 10"
      chapters: 
        - apuntes/clase-10.qmd

    - part: "Semana 11"
      chapters: 
        - apuntes/clase-11.qmd

    - part: "Semana 12"
      chapters: 
        - apuntes/clase-12.qmd

format:
  html:
    theme: cosmo
    fontsize: 16pt
    toc-title: Tabla de Contenidos
    toc-depth: 4
    css: style.css

execute:
  freeze: true