{
  "hash": "825a73be2c8861c027413005e1018acc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Pregunta 2\nauthor: Lucio Cornejo\nformat:\n  docx:\n    toc: true\n    toc-depth: 3\n  # html: \n  #   toc: true\n  #   toc-depth: 3\n  #   toc-location: left\n  #   theme: united\n  #   highlight: tango\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(nlme)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# load(\"./examen_final/pregunta-02/Presion.RData\")\nload(\"./Presion.RData\")\nstr(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t50 obs. of  4 variables:\n $ Paciente   : int  1 1 1 1 1 2 2 2 2 2 ...\n $ Semana     : int  1 2 3 4 5 1 2 3 4 5 ...\n $ Tratamiento: chr  \"Combinado\" \"Combinado\" \"Combinado\" \"Combinado\" ...\n $ Presion    : num  140 140 132 127 124 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Paciente Semana Tratamiento Presion\n1         1      1   Combinado   139.7\n2         1      2   Combinado   140.0\n3         1      3   Combinado   131.7\n4         1      4   Combinado   127.1\n5         1      5   Combinado   124.1\n6         2      1   Combinado   134.0\n7         2      2   Combinado   134.4\n8         2      3   Combinado   135.0\n9         2      4   Combinado   134.1\n10        2      5   Combinado   129.9\n11        3      1   Combinado   140.5\n12        3      2   Combinado   140.9\n13        3      3   Combinado   129.0\n14        3      4   Combinado   131.6\n15        3      5   Combinado   128.1\n16        4      1     Moderno   107.8\n17        4      2     Moderno   107.9\n18        4      3     Moderno   104.0\n19        4      4     Moderno   101.9\n20        4      5     Moderno   100.6\n21        5      1   Combinado   100.7\n22        5      2   Combinado   106.8\n23        5      3   Combinado   108.9\n24        5      4   Combinado   104.3\n25        5      5   Combinado   112.1\n26        6      1     Moderno   124.9\n27        6      2     Moderno   122.9\n28        6      3     Moderno   127.1\n29        6      4     Moderno   130.8\n30        6      5     Moderno   133.8\n31        7      1     Moderno   127.9\n32        7      2     Moderno   129.9\n33        7      3     Moderno   128.6\n34        7      4     Moderno   126.2\n35        7      5     Moderno   123.7\n36        8      1     Moderno   112.0\n37        8      2     Moderno   111.8\n38        8      3     Moderno   106.3\n39        8      4     Moderno   118.5\n40        8      5     Moderno   124.7\n41        9      1   Combinado   107.1\n42        9      2   Combinado   106.4\n43        9      3   Combinado   105.4\n44        9      4   Combinado   110.8\n45        9      5   Combinado   111.3\n46       10      1 Tradicional   122.9\n47       10      2 Tradicional   122.5\n48       10      3 Tradicional   122.0\n49       10      4 Tradicional   128.7\n50       10      5 Tradicional   126.7\n```\n\n\n:::\n:::\n\n\n\n\n\n## Item a\n\nCon el fin de emplear la variable categórica `Tratamiento`\nen el modelo, vamos a binarizarla y no emplear en los modelos\nla variable dummy asociada a tratamiento tradicional.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(datos$Tratamiento)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Combinado\"   \"Moderno\"     \"Tradicional\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos <- datos |>\n  mutate(D_M = Tratamiento == \"Moderno\") |>\n  mutate(D_C = Tratamiento == \"Combinado\")\ndatos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Paciente Semana Tratamiento Presion   D_M   D_C\n1         1      1   Combinado   139.7 FALSE  TRUE\n2         1      2   Combinado   140.0 FALSE  TRUE\n3         1      3   Combinado   131.7 FALSE  TRUE\n4         1      4   Combinado   127.1 FALSE  TRUE\n5         1      5   Combinado   124.1 FALSE  TRUE\n6         2      1   Combinado   134.0 FALSE  TRUE\n7         2      2   Combinado   134.4 FALSE  TRUE\n8         2      3   Combinado   135.0 FALSE  TRUE\n9         2      4   Combinado   134.1 FALSE  TRUE\n10        2      5   Combinado   129.9 FALSE  TRUE\n11        3      1   Combinado   140.5 FALSE  TRUE\n12        3      2   Combinado   140.9 FALSE  TRUE\n13        3      3   Combinado   129.0 FALSE  TRUE\n14        3      4   Combinado   131.6 FALSE  TRUE\n15        3      5   Combinado   128.1 FALSE  TRUE\n16        4      1     Moderno   107.8  TRUE FALSE\n17        4      2     Moderno   107.9  TRUE FALSE\n18        4      3     Moderno   104.0  TRUE FALSE\n19        4      4     Moderno   101.9  TRUE FALSE\n20        4      5     Moderno   100.6  TRUE FALSE\n21        5      1   Combinado   100.7 FALSE  TRUE\n22        5      2   Combinado   106.8 FALSE  TRUE\n23        5      3   Combinado   108.9 FALSE  TRUE\n24        5      4   Combinado   104.3 FALSE  TRUE\n25        5      5   Combinado   112.1 FALSE  TRUE\n26        6      1     Moderno   124.9  TRUE FALSE\n27        6      2     Moderno   122.9  TRUE FALSE\n28        6      3     Moderno   127.1  TRUE FALSE\n29        6      4     Moderno   130.8  TRUE FALSE\n30        6      5     Moderno   133.8  TRUE FALSE\n31        7      1     Moderno   127.9  TRUE FALSE\n32        7      2     Moderno   129.9  TRUE FALSE\n33        7      3     Moderno   128.6  TRUE FALSE\n34        7      4     Moderno   126.2  TRUE FALSE\n35        7      5     Moderno   123.7  TRUE FALSE\n36        8      1     Moderno   112.0  TRUE FALSE\n37        8      2     Moderno   111.8  TRUE FALSE\n38        8      3     Moderno   106.3  TRUE FALSE\n39        8      4     Moderno   118.5  TRUE FALSE\n40        8      5     Moderno   124.7  TRUE FALSE\n41        9      1   Combinado   107.1 FALSE  TRUE\n42        9      2   Combinado   106.4 FALSE  TRUE\n43        9      3   Combinado   105.4 FALSE  TRUE\n44        9      4   Combinado   110.8 FALSE  TRUE\n45        9      5   Combinado   111.3 FALSE  TRUE\n46       10      1 Tradicional   122.9 FALSE FALSE\n47       10      2 Tradicional   122.5 FALSE FALSE\n48       10      3 Tradicional   122.0 FALSE FALSE\n49       10      4 Tradicional   128.7 FALSE FALSE\n50       10      5 Tradicional   126.7 FALSE FALSE\n```\n\n\n:::\n:::\n\n\n\n\n\n**Modelo MCO**\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_1 <- lm(Presion ~ D_M + D_C, data = datos)\nsummary(modelo_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Presion ~ D_M + D_C, data = datos)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.256 -11.456   4.142   9.187  17.944 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  124.560      5.383  23.139   <2e-16 ***\nD_MTRUE       -5.995      6.019  -0.996    0.324    \nD_CTRUE       -1.604      5.897  -0.272    0.787    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.04 on 47 degrees of freedom\nMultiple R-squared:  0.03829,\tAdjusted R-squared:  -0.002635 \nF-statistic: 0.9356 on 2 and 47 DF,  p-value: 0.3995\n```\n\n\n:::\n:::\n\n\n\n\n\n**Prueba de homocedasticidad**\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlmtest::bptest(modelo_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modelo_1\nBP = 10.769, df = 2, p-value = 0.004587\n```\n\n\n:::\n:::\n\n\n\n\n\nEn base al p-valor $0.004587$ menor que $0.05$, concluimos que existe suficiente evidencia\npara afirmar que existe heterocedasticidad en los errores del modelo planteado.\n\n\n## Item b\n\nSe plantea un modelo donde se supone que la varianza es constante por tipo de \ntratamiento antihipertensivo.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos$Tratamiento <- as.factor(datos$Tratamiento)\ndatos$Tratamiento <- relevel(datos$Tratamiento, ref = \"Tradicional\")\n\nmodelo_2 <- gls(\n  Presion ~ Tratamiento,\n  data = datos,\n  weights = varIdent(form = ~1 | Tratamiento)\n)\nsummary(modelo_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized least squares fit by REML\n  Model: Presion ~ Tratamiento \n  Data: datos \n       AIC      BIC    logLik\n  378.3118 389.4127 -183.1559\n\nVariance function:\n Structure: Different standard deviations per stratum\n Formula: ~1 | Tratamiento \n Parameter estimates:\n  Combinado     Moderno Tradicional \n  1.0000000   0.7882693   0.2158846 \n\nCoefficients:\n                       Value Std.Error  t-value p-value\n(Intercept)          124.560  1.328006 93.79475  0.0000\nTratamientoCombinado  -1.604  3.054784 -0.52508  0.6020\nTratamientoModerno    -5.995  2.764385 -2.16866  0.0352\n\n Correlation: \n                     (Intr) TrtmnC\nTratamientoCombinado -0.435       \nTratamientoModerno   -0.480  0.209\n\nStandardized residuals:\n       Min         Q1        Med         Q3        Max \n-1.6568726 -0.9586436  0.3868891  0.8083552  1.4050907 \n\nResidual standard error: 13.75509 \nDegrees of freedom: 50 total; 47 residual\n```\n\n\n:::\n:::\n\n\n\n\n\nLa estimación obtenida por este modelo es de la forma\n\n$\\text{Presi\\'on}_{it} = 124.560 -5.995 D_{M,i} - 1.604 D_{C,i} + \\epsilon_{i,t}$\n\nAsimismo, se estimaron las siguientes varianzas, por tratamiento, de la presión:\n\n- Tratamiento **Tradicional**: $0.2158846$\n- Tratamiento **Moderno**: $0.7882693$\n- Tratamiento **Combinado**: $1.0000000$\n\nLa varianza más baja se encontró para el tratamiento tradicional, \nen particular, con un valor no tan lejano de cero; por lo cual\nla presión en ese grupo presenta poca dispersión.\n\nPor otro lado, se obtuvo una mayor varianza de presión para el tratamiento\nmoderno, casi el cuádruple de varianza, de hecho.\nSin embargo, la mayor dispersión de la presión se encuentra para los\npacientes que recibieron tratamiento combinado.\n\n## Item c\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_3 <- gls(\n  Presion ~ D_M + D_C,\n  data = datos,\n  correlation = corAR1(form = ~1),\n  method = \"ML\"\n)\nsummary(modelo_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized least squares fit by maximum likelihood\n  Model: Presion ~ D_M + D_C \n  Data: datos \n       AIC     BIC    logLik\n  336.0789 345.639 -163.0395\n\nCorrelation Structure: AR(1)\n Formula: ~1 \n Parameter estimate(s):\n      Phi \n0.8657756 \n\nCoefficients:\n                Value Std.Error   t-value p-value\n(Intercept) 131.51726  7.984635 16.471293  0.0000\nD_MTRUE      -8.22172  7.039433 -1.167952  0.2487\nD_CTRUE     -10.22953  6.312543 -1.620508  0.1118\n\n Correlation: \n        (Intr) D_MTRU\nD_MTRUE -0.629       \nD_CTRUE -0.642  0.881\n\nStandardized residuals:\n        Min          Q1         Med          Q3         Max \n-1.82554900 -0.97848449  0.00035867  0.61616835  1.57754098 \n\nResidual standard error: 12.43217 \nDegrees of freedom: 50 total; 47 residual\n```\n\n\n:::\n:::\n\n\n\n\n\nEcuación del modelo planteado:\n\n$\\text{Presi\\'on}_{it} = 131.51726 -8.22172 D_{M,i} - 10.22953 D_{C,i} + \\epsilon_{i,t}$\n\n## Item d\n\n## Item e\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}