<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lucio Enrique Cornejo Ramírez">
<meta name="dcterms.date" content="2025-06-17">

<title>Trabajo final</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-673ef696772ae3f5d735fbdc0f05a12f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-11cc6b83d3a89c75c242393bd9ef6be9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a>
  <ul class="collapse">
  <li><a href="#marco-del-problema" id="toc-marco-del-problema" class="nav-link" data-scroll-target="#marco-del-problema">Marco del problema</a></li>
  <li><a href="#plan-de-modelamiento" id="toc-plan-de-modelamiento" class="nav-link" data-scroll-target="#plan-de-modelamiento">Plan de modelamiento</a></li>
  </ul></li>
  <li><a href="#materiales-y-métodos" id="toc-materiales-y-métodos" class="nav-link" data-scroll-target="#materiales-y-métodos">Materiales y métodos</a>
  <ul class="collapse">
  <li><a href="#datosobservaciones" id="toc-datosobservaciones" class="nav-link" data-scroll-target="#datosobservaciones">Datos/Observaciones</a></li>
  <li><a href="#itinerario-metodológico-de-la-modelización" id="toc-itinerario-metodológico-de-la-modelización" class="nav-link" data-scroll-target="#itinerario-metodológico-de-la-modelización">Itinerario metodológico de la modelización</a></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">Resultados</a>
  <ul class="collapse">
  <li><a href="#carga-de-datos" id="toc-carga-de-datos" class="nav-link" data-scroll-target="#carga-de-datos">Carga de datos</a></li>
  <li><a href="#filtro-de-variables" id="toc-filtro-de-variables" class="nav-link" data-scroll-target="#filtro-de-variables">Filtro de variables</a></li>
  <li><a href="#modelamiento" id="toc-modelamiento" class="nav-link" data-scroll-target="#modelamiento">Modelamiento</a></li>
  <li><a href="#modelo-tras-remover-puntos-aberrantes" id="toc-modelo-tras-remover-puntos-aberrantes" class="nav-link" data-scroll-target="#modelo-tras-remover-puntos-aberrantes">Modelo tras remover puntos aberrantes</a></li>
  <li><a href="#selección-reducida-de-covariables" id="toc-selección-reducida-de-covariables" class="nav-link" data-scroll-target="#selección-reducida-de-covariables">Selección reducida de covariables</a></li>
  <li><a href="#modelo-final" id="toc-modelo-final" class="nav-link" data-scroll-target="#modelo-final">Modelo final</a></li>
  </ul></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión">Discusión</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lucio Enrique Cornejo Ramírez </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 17, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<section id="marco-del-problema" class="level3">
<h3 class="anchored" data-anchor-id="marco-del-problema">Marco del problema</h3>
<p>Entre los costos que más desastibilizan económicamente a las personas, se encuentra el pago por procedimientos médicos. Estos precios pueden variar en gran medida dependiendo de características del paciente, como detallaremos más adelante.</p>
<p>En ese sentido, resulta de gran valor predecir adecuadamente el costo que un seguro médico cubrirá, respecto a un procedimiento médico. Para un paciente, aquella predicción puede servir para que planifique qué tanto sería desestabilizado económicamente debido a algún tipo de procedimiento particular. Por otro lado, también para las aseguradoras resulta útil aquellas predicciones, ya que pueden anticipar qué tanto dinero estarían perdiendo por el monto a cubrir de la operación; además, con ese conocimiento pueden monitorear mejor qué pedidos de cobertura resultan anómalos, potencialmente fraudulentos.</p>
</section>
<section id="plan-de-modelamiento" class="level3">
<h3 class="anchored" data-anchor-id="plan-de-modelamiento">Plan de modelamiento</h3>
<p>Anteriormente, hemos planteado como variable por predecir a la cantidad monetaria que la aseguradora de un paciente cubrirá debido a un procedimiento médico. Note que aquel monto está muy relacionado al precio que paga el paciente luego que el seguro descuenta parte del costo del procedimiento médico … ese monto, que denominaremos <code>charges</code>, se intentará predecir.</p>
<p>Asimismo, vale recalcar la influencia de los gastos del hospital debido al procedimiento médico, variable que denotaremos <code>Hospital_expenditure</code>, sobre <code>charges</code>.</p>
<p>Para el modelamiento, se considerará además las siguientes características del paciente:</p>
<ul>
<li>Sexo (<code>age</code>)</li>
<li>Si fuma o no (<code>smoker</code>)</li>
<li>Región de la que provee (<code>region</code>)</li>
<li>Edad (<code>age</code>)</li>
<li>Índice de masa corporal (<code>bmi</code>)</li>
<li>Cantidad de hijos e hijas (<code>children</code>)</li>
<li>Costo médico que pagaría en caso no se aplicase seguro médico (<code>Claim_Amount</code>)</li>
<li>Número de procedimientos pasados (<code>past_consultations</code>)</li>
<li>Número de pasos que realizó en cierto día (<code>num_of_steps</code>)</li>
<li>Número de veces que ha sido hospitalizado (<code>Number_of_past_hospitalizations</code>)</li>
<li>Salario anual (<code>Anual_Salary</code>)</li>
</ul>
</section>
</section>
<section id="materiales-y-métodos" class="level2">
<h2 class="anchored" data-anchor-id="materiales-y-métodos">Materiales y métodos</h2>
<section id="datosobservaciones" class="level3">
<h3 class="anchored" data-anchor-id="datosobservaciones">Datos/Observaciones</h3>
<p>Las observaciones que consideraremos para este proyecto fueron descargadas de este sitio <a href="https://www.kaggle.com/datasets/shubhamsingh57/ml-model-practice-linear-regression/data">web</a>.</p>
<p>Estos datos son de distintos pacientes que recibieron algún tipo de tratamiento médico, de los cuales se tienen variables recopiladas, como edad, sexo, si fuma o no, etc. Así, descartamos que los datos consistan de una serie de tiempo.</p>
<p>No obstante, aquella página web no provee información más específica sobre el origen de los datos. Por ejemplo, si han sido recopilados en un único hospital, o en diversos hospitales, pero de qué país, etc.</p>
<p>Aún así, en esta investigación, no solo se considera la predicción de la variable mencionada, sino también cómo es que influyen las variables que emplearemos como regresores, en la predicción final. Por ejemplo, si su relación es directa o inversamente proporcional.</p>
<p>A continuación justificamos el posible uso de los caracteres presentes en los datos, como covariables:</p>
<ul>
<li><strong>Sexo</strong>: Debido al riesgo y costos distintos entre hombres y mujeres, para ciertos tipos de operaciones; por ejemplo, parto.</li>
<li><strong>Si fuma o no</strong>: Pues fumar aumenta la probabilidad de desarrollar complicaciones médicas</li>
<li><strong>Región de la que provee</strong>: Ya que el costo de un procedimiento médico puede variar mucho por región, así que también varía cuánto cubriría una aseguradora.</li>
<li><strong>Edad</strong>: Puesto que pacientes mayores suelen requerir más cuidados.</li>
<li><strong>Índice de masa corporal</strong>: En base a que un IMC elevado está asociado a mayores riesgos durante cirugías.</li>
<li><strong>Cantidad de hijos e hijas</strong>: Esto puede influir en el tipo de cobertura familiar (de seguro) que tiene el paciente.</li>
<li><strong>Costo médico que pagaría en caso no se aplicase seguro médico</strong>: Importante incluirlo, pues incluso se espera que presente una fuerte correlación positiva con la variable por predecir.</li>
<li><strong>Número de procedimientos pasados</strong>: Puede resultar útil en base a que pacientes con muchos procedimientos suelen tener enfermedades crónicas, por lo que se esperaría una mayor cobertura.</li>
<li><strong>Número de pasos que realizó en cierto día</strong>: Esta variable tampoco se explica en la fuente, pero la podemos considerar como una medida de la condición física de una persona, qué tan activa es.</li>
<li><strong>Número de veces que ha sido hospitalizado</strong>: Pues más hospitalizaciones implican mayor riesgo en la operación, aumentando posiblemente así los costos que cubre la aseguradora.</li>
<li><strong>Salario anual</strong>: Como indicador de nivel socioeconómico, se espera que pacientes con ingresos altos cuenten con aseguradoras que cubren mayor parte el costo por intervención médica.</li>
</ul>
</section>
<section id="itinerario-metodológico-de-la-modelización" class="level3">
<h3 class="anchored" data-anchor-id="itinerario-metodológico-de-la-modelización">Itinerario metodológico de la modelización</h3>
<p>A continuación, describrimos los pasos a seguir para la construcción de diferentes modelos de predicción:</p>
<ol type="1">
<li><p>Descarte de observaciones que presenten algún valor faltante para cualquier variable.</p></li>
<li><p>Gráficos de dispersión para pares de variables</p></li>
<li><p>Debido al máximo establecido en este proyecto, respecto al número de covariables, calculamos las correlaciones múltiples</p></li>
<li><p>Filtro de observaciones al azar, debido a máximo establecido en este proyecto.</p></li>
<li><p>Limpieza de datos</p></li>
<li><p>Construcción del modelo OLS, empleando todas las covariables</p></li>
<li><p>Gráficos de valores observados y residuos contra valores estimados. Interpretar R^2</p></li>
<li><p>Emplear el test de Levine y Shapiro para averiguar la homocedasticidad y la normalidad.</p></li>
<li><p>En caso positivo, evaluar por medio de ANOVA si el modelo tiene sentido. En caso positivo, determinar qué variables explicativas tienen sentido.</p></li>
<li><p>Si se encuentran puntos aberrantes, recorrer el modelo sin aquellos y repetir los pasos mencionados.</p></li>
<li><p>Emplear selección por delante, para atrás y stepwise.</p></li>
<li><p>Ejecutar los tests de tipo ANOVA</p></li>
<li><p>En caso el test ANOVA relevante resulte positivo, incluir los tests post-hoc.</p></li>
</ol>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">Resultados</h2>
<section id="carga-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="carga-de-datos">Carga de datos</h3>
<p>A continuación, mostramos los datos descargados del sitio web mencionado en la sección previa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"./new_insurance_data.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,338
Columns: 13
$ age                             &lt;dbl&gt; 18, 18, 18, 18, 18, 18, 18, 18, 18, 18~
$ sex                             &lt;chr&gt; "male", "male", "male", "male", "male"~
$ bmi                             &lt;dbl&gt; 23.21, 30.14, 33.33, 33.66, 34.10, 34.~
$ children                        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
$ smoker                          &lt;chr&gt; "no", "no", "no", "no", "no", "no", "n~
$ Claim_Amount                    &lt;dbl&gt; 29087.543, 39053.674, 39023.628, 28185~
$ past_consultations              &lt;dbl&gt; 17, 7, 19, 11, 16, 20, 13, 12, 17, 19,~
$ num_of_steps                    &lt;dbl&gt; 715428, 699157, 702341, 700250, 711584~
$ Hospital_expenditure            &lt;dbl&gt; 4720921.0, 4329831.7, 6884860.8, 42747~
$ Number_of_past_hospitalizations &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA~
$ Anual_Salary                    &lt;dbl&gt; 55784970, 13700885, 73523107, 75819680~
$ region                          &lt;chr&gt; "southeast", "southeast", "southeast",~
$ charges                         &lt;dbl&gt; 1121.874, 1131.507, 1135.941, 1136.399~</code></pre>
</div>
</div>
<p>Descartamos las observaciones con alguna variable faltante.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cantidad de observaciones</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1338</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cantidad de observaciones con alguna variable faltante</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">complete.cases</span>(datos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="filtro-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="filtro-de-variables">Filtro de variables</h3>
<section id="graficos-de-dispersión" class="level4">
<h4 class="anchored" data-anchor-id="graficos-de-dispersión">Graficos de dispersión</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>covariables_numericas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"age"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"bmi"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"children"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Claim_Amount"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"past_consultations"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"num_of_steps"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hospital_expenditure"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Number_of_past_hospitalizations"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Anual_Salary"</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>columnas_numericas <span class="ot">&lt;-</span> <span class="fu">c</span>(covariables_numericas, <span class="st">"charges"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(datos[, columnas_numericas])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nótese que la variable por predecir, <code>charges</code>, parece presentar una relación lineal con la covariable <code>Annual_Salary</code>. Asimismo, parece haber indicios de que resulta posible transformar las variables <code>num_of_steps</code> y <code>Hospital_expenditure</code> por funciones logaritmo y exponcial, respectivamente, con fin que se tenga una fuerte relación lineal entre el predictor creado y la variable por predecir.</p>
</section>
<section id="correlaciones-parciales-entre-covariables" class="level4">
<h4 class="anchored" data-anchor-id="correlaciones-parciales-entre-covariables">Correlaciones parciales entre covariables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d.cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(datos[, covariables_numericas])</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>d.inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(d.cor)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>d.corm <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1-1</span><span class="sc">/</span><span class="fu">diag</span>(d.inv))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">length</span>(d.corm)  </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>d.part <span class="ot">&lt;-</span> d.inv</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>pd) {</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>)) {</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    d.part[i,j] <span class="ot">&lt;-</span> <span class="sc">-</span>d.inv[i,j]<span class="sc">/</span><span class="fu">sqrt</span>(d.inv[i,i]<span class="sc">*</span>d.inv[j,j])</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  d.part[i,i] <span class="ot">&lt;-</span> d.corm[i]</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  d.part[<span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>),i] <span class="ot">&lt;-</span> d.part[i,<span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>)]  </span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>d.part</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        age          bmi     children
age                              0.66869810  0.125138033 -0.127797419
bmi                              0.12513803  0.283723310  0.027431191
children                        -0.12779742  0.027431191  0.285534954
Claim_Amount                    -0.04743308  0.019145260 -0.007971203
past_consultations              -0.03242764  0.002848758  0.011798696
num_of_steps                     0.58296028 -0.073153318  0.147382251
Hospital_expenditure             0.30690425  0.031794571  0.128345835
Number_of_past_hospitalizations -0.02225606 -0.018175497  0.140432728
Anual_Salary                    -0.38460223  0.034625132 -0.173171362
                                Claim_Amount past_consultations num_of_steps
age                             -0.047433079       -0.032427643   0.58296028
bmi                              0.019145260        0.002848758  -0.07315332
children                        -0.007971203        0.011798696   0.14738225
Claim_Amount                     0.439018730       -0.005991357   0.09098912
past_consultations              -0.005991357        0.630532156   0.13217102
num_of_steps                     0.090989121        0.132171021   0.93080551
Hospital_expenditure            -0.016667332       -0.087954734  -0.49727359
Number_of_past_hospitalizations  0.023096940       -0.056723682   0.45898240
Anual_Salary                     0.052074797        0.162444557   0.56078648
                                Hospital_expenditure
age                                       0.30690425
bmi                                       0.03179457
children                                  0.12834583
Claim_Amount                             -0.01666733
past_consultations                       -0.08795473
num_of_steps                             -0.49727359
Hospital_expenditure                      0.98147153
Number_of_past_hospitalizations          -0.04913622
Anual_Salary                              0.95773182
                                Number_of_past_hospitalizations Anual_Salary
age                                                 -0.02225606  -0.38460223
bmi                                                 -0.01817550   0.03462513
children                                             0.14043273  -0.17317136
Claim_Amount                                         0.02309694   0.05207480
past_consultations                                  -0.05672368   0.16244456
num_of_steps                                         0.45898240   0.56078648
Hospital_expenditure                                -0.04913622   0.95773182
Number_of_past_hospitalizations                      0.86849267   0.13449231
Anual_Salary                                         0.13449231   0.98774064</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>vals_diag <span class="ot">&lt;-</span> <span class="fu">diag</span>(d.part)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>max_col_indices <span class="ot">&lt;-</span> <span class="fu">apply</span>(d.part, <span class="dv">1</span>, which.max)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>idx_ordenados <span class="ot">&lt;-</span> <span class="fu">order</span>(vals_diag, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ordenados_vals_diag <span class="ot">&lt;-</span> vals_diag[idx_ordenados]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>ordenados_max_cols <span class="ot">&lt;-</span> max_col_indices[idx_ordenados]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">correlacion_parcial =</span> ordenados_vals_diag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                correlacion_parcial
Anual_Salary                              0.9877406
Hospital_expenditure                      0.9814715
num_of_steps                              0.9308055
Number_of_past_hospitalizations           0.8684927
age                                       0.6686981
past_consultations                        0.6305322
Claim_Amount                              0.4390187
children                                  0.2855350
bmi                                       0.2837233</code></pre>
</div>
</div>
<p>Note que cuatro covariables presentan correlación parcial mayor a 0.8, en orden descendente <code>Anual_Salary</code>, <code>Hospital_expenditure</code>, <code>num_of_steps</code> y <code>Number_of_past_hospitalizations</code>. Aquellas variables son muy explicadas por las demás (posible multicolinearidad).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Inspeccionemos ahora, de manera particular, las correlaciones entre covariables</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observamos una alta correlación entre <code>Anual_Salary</code> y <code>Hospital_expenditure</code>, con un valor de 0.9692177. Asimismo, como la variable de salario anual es más sencilla de recopilar (por ejemplo, en una encuesta) que la de gasto de hospital, descartamos la variable cuantitativa <code>Hospital_expenditure</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Anual_Salary, <span class="at">y =</span> Hospital_expenditure)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Salario anual"</span>, <span class="at">y =</span> <span class="st">"Gasto del hospital"</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variable-cuantitativa-num_of_steps" class="level4">
<h4 class="anchored" data-anchor-id="variable-cuantitativa-num_of_steps">Variable cuantitativa <code>num_of_steps</code></h4>
<p>Inicialmente se consideró descartar la variable referente al número de pasos que realizó el paciente en cierto día. Esto pues, a primera vista, no se esperaría que tal información resulte relevante para el costo final por el procedimiento médico.</p>
<p>Graficamos tal posible regreso contra la variable respuesta:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> num_of_steps, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Número de pasos"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a que la relación parece asemejarse a una exponencial, graficamos la variable <code>num_of_steps</code> contra el logaritmo de la variable respuesta:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">scaled_rsp =</span> <span class="fu">log</span>(charges)) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> num_of_steps, <span class="at">y =</span> scaled_rsp)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Número de pasos"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a que aquella relación parece ser <em>aproximadamente</em> lineal, optamos por no descartar la variable cuantitativa <code>num_of_steps</code>.</p>
</section>
<section id="variable-cuantitativa-age" class="level4">
<h4 class="anchored" data-anchor-id="variable-cuantitativa-age">Variable cuantitativa <code>age</code></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Edad"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variable-cuantitativa-bmi" class="level4">
<h4 class="anchored" data-anchor-id="variable-cuantitativa-bmi">Variable cuantitativa <code>bmi</code></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Índice de masa corporal"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variable-cuantitativa-children" class="level4">
<h4 class="anchored" data-anchor-id="variable-cuantitativa-children">Variable cuantitativa <code>children</code></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> children, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Número de hijos"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variable-cuantitativa-past_consultations" class="level4">
<h4 class="anchored" data-anchor-id="variable-cuantitativa-past_consultations">Variable cuantitativa <code>past_consultations</code></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> past_consultations, <span class="at">y =</span> charges)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Número de procedimientos pasados"</span>, <span class="at">y =</span> <span class="st">"Pago final"</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Descartamos la variable cuantitativa <code>children</code>, pues, en base a este simple análisis inicial, no parece indicar algún de tipo de relación lineal con la variable por predecir. Es más, su gráfico de dispersión parece sugerir que consideremos a la variable <code>children</code> como cualitativa.</p>
</section>
<section id="variables-categóricas" class="level4">
<h4 class="anchored" data-anchor-id="variables-categóricas">Variables categóricas</h4>
<p>Para el filtro de variables categóricas, descartaremos aquella para la cual las distribuciones de la variable respuesta, respecto a los valores de aquella variable categórica sean relativamente similares.</p>
</section>
<section id="variable-cualitativa-region" class="level4">
<h4 class="anchored" data-anchor-id="variable-cualitativa-region">Variable cualitativa <code>region</code></h4>
<p>Inspeccionamos la distribución de la variable respuesta, respecto a los valores de la variable categórica <code>region</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> charges, <span class="at">color =</span> region, <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">"Densidad de 'charges' para cada categoría de 'region'"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">"charges"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">"Densidad"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En base a que aquellas funciones densidad no presentan una difencia resaltante, descartaremos la variable <code>region</code>. De esa manera, las variables cualitativas que emplearemos para esta investigación son solo <code>sex</code> y <code>smoker</code>.</p>
</section>
<section id="variables-finales" class="level4">
<h4 class="anchored" data-anchor-id="variables-finales">Variables finales</h4>
<ul>
<li>Variables cualitativas:
<ul>
<li><code>sex</code></li>
<li><code>smoker</code></li>
</ul></li>
<li>Variables cuantitativas:
<ul>
<li><code>age</code></li>
<li><code>bmi</code></li>
<li><code>Claim_Amount</code></li>
<li><code>past_consultations</code></li>
<li><code>num_of_steps</code></li>
<li><code>Number_of_past_hospitalizations</code></li>
<li><code>Anual_Salary</code></li>
<li><code>charges</code> (<strong>variable respuesta</strong>)</li>
</ul></li>
</ul>
<p>Para limitarnos a 500 filas, según la restricción de este proyecto, realizaremos un muestreo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    sex,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    smoker,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    age,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    bmi,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    Claim_Amount,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    past_consultations,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    num_of_steps,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    Number_of_past_hospitalizations,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    Anual_Salary,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    charges</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">sample_n</span>(obs, <span class="dv">500</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>openxlsx<span class="sc">::</span><span class="fu">write.xlsx</span>(obs, <span class="st">'./datos.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="modelamiento" class="level3">
<h3 class="anchored" data-anchor-id="modelamiento">Modelamiento</h3>
<p>Note que los tipos de datos de las covariables son adecuadas. En particular, las funciones por emplear se encargarán de la conversión numérica a las covariables categóricas <code>age</code> y <code>sex</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 500
Columns: 10
$ sex                             &lt;chr&gt; "male", "female", "male", "female", "m~
$ smoker                          &lt;chr&gt; "no", "no", "yes", "no", "no", "no", "~
$ age                             &lt;dbl&gt; 28, 40, 33, 48, 63, 48, 59, 38, 63, 22~
$ bmi                             &lt;dbl&gt; 33.820, 41.420, 27.100, 28.880, 31.445~
$ Claim_Amount                    &lt;dbl&gt; 24107.866, 27534.303, 39952.923, 45755~
$ past_consultations              &lt;dbl&gt; 18, 15, 27, 24, 14, 18, 18, 12, 11, 8,~
$ num_of_steps                    &lt;dbl&gt; 983349, 1031312, 996320, 912509, 95335~
$ Number_of_past_hospitalizations &lt;dbl&gt; 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1,~
$ Anual_Salary                    &lt;dbl&gt; 481649496, 869010594, 453727467, 17846~
$ charges                         &lt;dbl&gt; 19673.336, 28476.735, 19040.876, 9249.~</code></pre>
</div>
</div>
<p>Comencemos definiendo algunas funciones auxliares en el análisis y modelamiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sum.lm <span class="ot">&lt;-</span> <span class="cf">function</span>(lmod) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  summ <span class="ot">&lt;-</span> <span class="fu">summary</span>(lmod)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(lmod)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  summ<span class="sc">$</span>coefficients <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    summ<span class="sc">$</span>coefficients[,<span class="dv">1</span>],</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    ci,summ<span class="sc">$</span>coefficients[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(summ)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>extraer_estadistica_f <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">summary</span>(modelo)<span class="sc">$</span>fstatistic[<span class="dv">1</span>])</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>obtener_p_valor_de_estadistica_f <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  fval <span class="ot">&lt;-</span> s<span class="sc">$</span>fstatistic[<span class="st">"value"</span>]</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  df1 <span class="ot">&lt;-</span> s<span class="sc">$</span>fstatistic[<span class="st">"numdf"</span>]</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  df2 <span class="ot">&lt;-</span> s<span class="sc">$</span>fstatistic[<span class="st">"dendf"</span>]</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">pf</span>(fval, df1, df2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>extraer_info_t_student <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(modelo)<span class="sc">$</span>coefficients)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df[<span class="sc">-</span><span class="dv">1</span>, <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>)]</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>es_significativo <span class="ot">&lt;-</span> df[, <span class="dv">2</span>] <span class="sc">&lt;</span> <span class="fl">0.05</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Implementación básica de la función car::ncvTest, debido a que</span></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co"># no me funciona descargar aquella librería.</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>ncvTest <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo, <span class="at">variable =</span> <span class="cn">NULL</span>) {</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verifica si el modelo es lineal</span></span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">inherits</span>(modelo, <span class="st">"lm"</span>)) <span class="fu">stop</span>(<span class="st">"El modelo debe ser de clase 'lm'"</span>)</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extrae los residuos y los valores ajustados</span></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>  residuos <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo)</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>  ajustados <span class="ot">&lt;-</span> <span class="fu">fitted</span>(modelo)</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Selecciona la variable de prueba</span></span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(variable)) {</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> ajustados  <span class="co"># por defecto, se usa contra los valores ajustados</span></span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>    datos_modelo <span class="ot">&lt;-</span> <span class="fu">model.frame</span>(modelo)</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> datos_modelo[[variable]]</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.null</span>(z)) <span class="fu">stop</span>(<span class="st">"Variable no encontrada en el marco del modelo"</span>)</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcula la estadística de prueba</span></span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a>  score <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuos<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> z)</span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a>  informacion <span class="ot">&lt;-</span> <span class="fu">sum</span>((residuos <span class="sc">*</span> z)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a>  estadistico <span class="ot">&lt;-</span> score<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> informacion</span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcula el valor p</span></span>
<span id="cb25-58"><a href="#cb25-58" aria-hidden="true" tabindex="-1"></a>  valor_p <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(estadistico, <span class="at">df =</span> <span class="dv">1</span>)</span>
<span id="cb25-59"><a href="#cb25-59" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-60"><a href="#cb25-60" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Devuelve como objeto de prueba</span></span>
<span id="cb25-61"><a href="#cb25-61" aria-hidden="true" tabindex="-1"></a>  resultado <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">statistic =</span> estadistico, <span class="at">p.value =</span> valor_p)</span>
<span id="cb25-62"><a href="#cb25-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>(resultado) <span class="ot">&lt;-</span> <span class="st">"htest"</span></span>
<span id="cb25-63"><a href="#cb25-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(resultado)</span>
<span id="cb25-64"><a href="#cb25-64" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-65"><a href="#cb25-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-66"><a href="#cb25-66" aria-hidden="true" tabindex="-1"></a>resaltar_n_puntos_con_mayor_apalancamiento <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo, <span class="at">n =</span> <span class="dv">10</span>) {</span>
<span id="cb25-67"><a href="#cb25-67" aria-hidden="true" tabindex="-1"></a>  graficos <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb25-68"><a href="#cb25-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-69"><a href="#cb25-69" aria-hidden="true" tabindex="-1"></a>  observaciones <span class="ot">&lt;-</span> modelo<span class="sc">$</span>model[[<span class="dv">1</span>]]</span>
<span id="cb25-70"><a href="#cb25-70" aria-hidden="true" tabindex="-1"></a>  estimaciones <span class="ot">&lt;-</span> modelo<span class="sc">$</span>fitted.values</span>
<span id="cb25-71"><a href="#cb25-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-72"><a href="#cb25-72" aria-hidden="true" tabindex="-1"></a>  graficos<span class="sc">$</span>est_vs_obs <span class="ot">&lt;-</span> <span class="cf">function</span> () {</span>
<span id="cb25-73"><a href="#cb25-73" aria-hidden="true" tabindex="-1"></a>    abs_resid <span class="ot">&lt;-</span> <span class="fu">abs</span>(observaciones <span class="sc">-</span> estimaciones)</span>
<span id="cb25-74"><a href="#cb25-74" aria-hidden="true" tabindex="-1"></a>    top10_idx <span class="ot">&lt;-</span> <span class="fu">order</span>(abs_resid, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span>n]</span>
<span id="cb25-75"><a href="#cb25-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-76"><a href="#cb25-76" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(</span>
<span id="cb25-77"><a href="#cb25-77" aria-hidden="true" tabindex="-1"></a>      estimaciones, </span>
<span id="cb25-78"><a href="#cb25-78" aria-hidden="true" tabindex="-1"></a>      observaciones,</span>
<span id="cb25-79"><a href="#cb25-79" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="fu">ifelse</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(observaciones) <span class="sc">%in%</span> top10_idx, <span class="st">"red"</span>, <span class="st">"black"</span>),</span>
<span id="cb25-80"><a href="#cb25-80" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb25-81"><a href="#cb25-81" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"estimaciones"</span>,</span>
<span id="cb25-82"><a href="#cb25-82" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">"observaciones"</span></span>
<span id="cb25-83"><a href="#cb25-83" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-84"><a href="#cb25-84" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">0</span>, <span class="at">b =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb25-85"><a href="#cb25-85" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="fu">lm</span>(observaciones <span class="sc">~</span> estimaciones), <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb25-86"><a href="#cb25-86" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-87"><a href="#cb25-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-88"><a href="#cb25-88" aria-hidden="true" tabindex="-1"></a>  graficos<span class="sc">$</span>est_vs_res <span class="ot">&lt;-</span> <span class="cf">function</span> () {</span>
<span id="cb25-89"><a href="#cb25-89" aria-hidden="true" tabindex="-1"></a>    residuos <span class="ot">&lt;-</span> modelo<span class="sc">$</span>residuals</span>
<span id="cb25-90"><a href="#cb25-90" aria-hidden="true" tabindex="-1"></a>    abs_resid <span class="ot">&lt;-</span> <span class="fu">abs</span>(residuos)</span>
<span id="cb25-91"><a href="#cb25-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-92"><a href="#cb25-92" aria-hidden="true" tabindex="-1"></a>    top10_idx <span class="ot">&lt;-</span> <span class="fu">order</span>(abs_resid, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span>n]</span>
<span id="cb25-93"><a href="#cb25-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-94"><a href="#cb25-94" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(</span>
<span id="cb25-95"><a href="#cb25-95" aria-hidden="true" tabindex="-1"></a>      estimaciones, </span>
<span id="cb25-96"><a href="#cb25-96" aria-hidden="true" tabindex="-1"></a>      residuos,</span>
<span id="cb25-97"><a href="#cb25-97" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="fu">ifelse</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(residuos) <span class="sc">%in%</span> top10_idx, <span class="st">"red"</span>, <span class="st">"black"</span>),</span>
<span id="cb25-98"><a href="#cb25-98" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb25-99"><a href="#cb25-99" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"estimaciones"</span>,</span>
<span id="cb25-100"><a href="#cb25-100" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">"residuos"</span></span>
<span id="cb25-101"><a href="#cb25-101" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-102"><a href="#cb25-102" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb25-103"><a href="#cb25-103" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-104"><a href="#cb25-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-105"><a href="#cb25-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(graficos)</span>
<span id="cb25-106"><a href="#cb25-106" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-107"><a href="#cb25-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-108"><a href="#cb25-108" aria-hidden="true" tabindex="-1"></a>calcular_rse <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb25-109"><a href="#cb25-109" aria-hidden="true" tabindex="-1"></a>  k <span class="ot">&lt;-</span> <span class="fu">length</span>(modelo<span class="sc">$</span>coefficients) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb25-110"><a href="#cb25-110" aria-hidden="true" tabindex="-1"></a>  SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(modelo<span class="sc">$</span>residuals<span class="sc">**</span><span class="dv">2</span>)</span>
<span id="cb25-111"><a href="#cb25-111" aria-hidden="true" tabindex="-1"></a>  num_obs <span class="ot">&lt;-</span> <span class="fu">length</span>(modelo<span class="sc">$</span>residuals)</span>
<span id="cb25-112"><a href="#cb25-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-113"><a href="#cb25-113" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sqrt</span>(SSE<span class="sc">/</span>(num_obs <span class="sc">-</span> (<span class="dv">1</span><span class="sc">+</span>k))))</span>
<span id="cb25-114"><a href="#cb25-114" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="modelo-completo" class="level4">
<h4 class="anchored" data-anchor-id="modelo-completo">Modelo completo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>modelo_completo <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> ., obs)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ ., data = obs)

Residuals:
    Min      1Q  Median      3Q     Max 
-3574.8  -728.0  -121.6   631.4  3762.3 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.223e+04 -4.430e+04 -4.016e+04  1.055e+03
sexmale                          1.018e+02 -9.310e+01  2.967e+02  9.919e+01
smokeryes                        3.807e+02 -1.072e+02  8.686e+02  2.483e+02
age                             -2.649e+01 -3.670e+01 -1.628e+01  5.196e+00
bmi                             -1.680e+01 -3.465e+01  1.046e+00  9.083e+00
Claim_Amount                     2.238e-03 -4.649e-03  9.125e-03  3.505e-03
past_consultations               7.868e-01 -1.567e+01  1.725e+01  8.378e+00
num_of_steps                     5.771e-02  5.491e-02  6.051e-02  1.427e-03
Number_of_past_hospitalizations -1.022e+03 -1.405e+03 -6.391e+02  1.950e+02
Anual_Salary                     1.451e-05  1.411e-05  1.490e-05  2.028e-07
                                t value Pr(&gt;|t|)    
(Intercept)                     -40.029  &lt; 2e-16 ***
sexmale                           1.026    0.305    
smokeryes                         1.533    0.126    
age                              -5.097 4.93e-07 ***
bmi                              -1.850    0.065 .  
Claim_Amount                      0.639    0.523    
past_consultations                0.094    0.925    
num_of_steps                     40.434  &lt; 2e-16 ***
Number_of_past_hospitalizations  -5.242 2.37e-07 ***
Anual_Salary                     71.542  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1092 on 490 degrees of freedom
Multiple R-squared:  0.991, Adjusted R-squared:  0.9908 
F-statistic:  5977 on 9 and 490 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>En base al valor del <span class="math inline">\(R^2\)</span>, note que este modelo explica alrededor del <strong>99.1%</strong> de la varianza de <code>charges</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  modelo_completo<span class="sc">$</span>fitted.values,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  obs<span class="sc">$</span>charges,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"Estimados"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"Observados"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  modelo_completo<span class="sc">$</span>fitted.values,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  modelo_completo<span class="sc">$</span>residuals, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"estimados"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"residuos"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tests" class="level4">
<h4 class="anchored" data-anchor-id="tests">Tests</h4>
<p><strong>Prueba de homocedasticidad</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>


data:  
= 351173941, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>En base al p-valor menor a 0.05, se tiene suficiente evidencia de que la <strong>varianza de los residuos no es constante</strong>, es decir, no se cumple la homocedasticidad.</p>
<p><strong>Prueba de normalidad de los errores</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>qq_completo <span class="ot">&lt;-</span> <span class="fu">qqnorm</span>(modelo_completo<span class="sc">$</span>residuals)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(modelo_completo<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(modelo_completo<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  modelo_completo$residuals
W = 0.98331, p-value = 1.677e-05</code></pre>
</div>
</div>
<p>En base al p-valor menor a 0.05, contamos con suficiente evidencia para afirmar que los <strong>residuos no siguen una distribución normal</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">rstandard</span>(modelo_completo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rstandard(modelo_completo)
W = 0.98249, p-value = 1.01e-05</code></pre>
</div>
</div>
<p>Al ejecutar el test para los residuos estandarizados, se llega a la misma conclusión respecto a la normalidad de los residuos.</p>
<p>Como se ha fallado en ambos tests, no estamos en condición formal de aplicar ANOVA. Sin embargo, inspeccionemos su resultado de todas maneras, según la tabla de análisis de la varianza.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: charges
                                 Df     Sum Sq    Mean Sq  F value    Pr(&gt;F)
sex                               1 5.6614e+08 5.6614e+08   474.88 &lt; 2.2e-16
smoker                            1 3.9087e+10 3.9087e+10 32786.75 &lt; 2.2e-16
age                               1 7.7570e+09 7.7570e+09  6506.60 &lt; 2.2e-16
bmi                               1 1.6345e+09 1.6345e+09  1371.07 &lt; 2.2e-16
Claim_Amount                      1 6.8192e+08 6.8192e+08   572.00 &lt; 2.2e-16
past_consultations                1 1.3044e+09 1.3044e+09  1094.15 &lt; 2.2e-16
num_of_steps                      1 6.3277e+09 6.3277e+09  5307.70 &lt; 2.2e-16
Number_of_past_hospitalizations   1 6.6481e+08 6.6481e+08   557.65 &lt; 2.2e-16
Anual_Salary                      1 6.1018e+09 6.1018e+09  5118.27 &lt; 2.2e-16
Residuals                       490 5.8416e+08 1.1922e+06                   
                                   
sex                             ***
smoker                          ***
age                             ***
bmi                             ***
Claim_Amount                    ***
past_consultations              ***
num_of_steps                    ***
Number_of_past_hospitalizations ***
Anual_Salary                    ***
Residuals                          
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extraer_estadistica_f</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
5976.563 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">obtener_p_valor_de_estadistica_f</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>value 
    0 </code></pre>
</div>
</div>
<p>Como el p-valor es mucho menor que 0.05, concluimos que este modelo tiene sentido. En particular, existe alguna covariable que explica significativamente la varianza asociada a <code>charges</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extraer_info_t_student</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                    t value      Pr(&gt;|t|) es_significativo
sexmale                          1.02617973  3.053132e-01            FALSE
smokeryes                        1.53299676  1.259220e-01            FALSE
age                             -5.09735180  4.927953e-07             TRUE
bmi                             -1.84969716  6.495914e-02            FALSE
Claim_Amount                     0.63850065  5.234461e-01            FALSE
past_consultations               0.09390782  9.252208e-01            FALSE
num_of_steps                    40.43404893 3.256649e-158             TRUE
Number_of_past_hospitalizations -5.24178980  2.368235e-07             TRUE
Anual_Salary                    71.54209305 1.626762e-261             TRUE</code></pre>
</div>
</div>
<p>Por otro lado, según este otro test, solo se puede afirmar para las variables <code>age</code>, <code>num_of_steps</code>, <code>Number_of_past_hospitalizations</code> y <code>Anual_Salary</code> que tienen sentido en el modelo.</p>
</section>
<section id="puntos-aberrantes" class="level4">
<h4 class="anchored" data-anchor-id="puntos-aberrantes">Puntos aberrantes</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>modelo_completo.cd <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(modelo_completo)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>modelo_completo.mcd <span class="ot">&lt;-</span> <span class="fu">mean</span>(modelo_completo.cd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Puntos más lejos de 3 promedios</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>modelo_completo.cooked_1 <span class="ot">&lt;-</span> <span class="fu">which</span>(modelo_completo.cd <span class="sc">&gt;</span> <span class="dv">3</span><span class="sc">*</span>modelo_completo.mcd)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>modelo_completo.cooked_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2  11  14  19  29  31  68  78  85 106 129 138 162 168 223 225 240 242 258 260 
  2  11  14  19  29  31  68  78  85 106 129 138 162 168 223 225 240 242 258 260 
267 292 299 316 329 331 347 362 365 373 385 396 412 449 453 455 486 496 
267 292 299 316 329 331 347 362 365 373 385 396 412 449 453 455 486 496 </code></pre>
</div>
</div>
<p>Según aquel criterio, se tienen 38 puntos aberrantes … una cantidad significativa.</p>
<p><strong>Puntos más lejos de cuatro veces los regresores</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>modelo_completo.cooked_2 <span class="ot">&lt;-</span> <span class="fu">which</span>(modelo_completo.cd <span class="sc">&gt;</span> (<span class="dv">4</span> <span class="sc">/</span> <span class="fu">dim</span>(obs)))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>modelo_completo.cooked_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 11  19  29  31  85 129 223 225 263 267 299 329 331 347 365 373 385 449 453 455 
 11  19  29  31  85 129 223 225 263 267 299 329 331 347 365 373 385 449 453 455 </code></pre>
</div>
</div>
<p>Según este otro criterio, se tienen 20 puntos aberrantes, también una cantidad significativa.</p>
<p><strong>Mayores apalancamientos</strong>: Resaltamos en rojo los 10 puntos con mayor apalancamiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>modelo_completo.graficos_apalancamiento <span class="ot">&lt;-</span> <span class="fu">resaltar_n_puntos_con_mayor_apalancamiento</span>(modelo_completo, <span class="dv">10</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>modelo_completo.graficos_apalancamiento<span class="sc">$</span><span class="fu">est_vs_obs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>modelo_completo.graficos_apalancamiento<span class="sc">$</span><span class="fu">est_vs_res</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modelo-tras-remover-puntos-aberrantes" class="level3">
<h3 class="anchored" data-anchor-id="modelo-tras-remover-puntos-aberrantes">Modelo tras remover puntos aberrantes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>obs_sin_aber <span class="ot">&lt;-</span> obs[<span class="sc">-</span>modelo_completo.cooked_1,]</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>obs_sin_aber</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 462 x 10
   sex    smoker   age   bmi Claim_Amount past_consultations num_of_steps
   &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;              &lt;dbl&gt;        &lt;dbl&gt;
 1 male   no        28  33.8       24108.                 18       983349
 2 male   yes       33  27.1       39953.                 27       996320
 3 female no        48  28.9       45756.                 24       912509
 4 male   no        63  31.4       34046.                 14       953355
 5 male   no        48  34.3       36944.                 18       926940
 6 female no        59  32.4       44302.                 18       940460
 7 male   no        38  34.7        8821.                 12       880463
 8 female no        63  31.8       26904.                 11       954102
 9 female no        22  24.3        5289.                  8       764144
10 female no        54  31.9       41178.                 24       919493
# i 452 more rows
# i 3 more variables: Number_of_past_hospitalizations &lt;dbl&gt;,
#   Anual_Salary &lt;dbl&gt;, charges &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mod_com_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> ., obs_sin_aber)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(mod_com_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ ., data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2250.13  -580.13   -19.38   534.20  2564.82 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.026e+04 -4.196e+04 -3.857e+04  8.628e+02
sexmale                         -3.150e+01 -1.801e+02  1.172e+02  7.564e+01
smokeryes                        8.137e+02  3.846e+02  1.243e+03  2.183e+02
age                             -1.011e+01 -1.887e+01 -1.348e+00  4.457e+00
bmi                             -9.743e+00 -2.315e+01  3.664e+00  6.823e+00
Claim_Amount                    -1.612e-03 -6.884e-03  3.660e-03  2.683e-03
past_consultations               4.894e+00 -7.653e+00  1.744e+01  6.384e+00
num_of_steps                     5.521e-02  5.288e-02  5.754e-02  1.185e-03
Number_of_past_hospitalizations -1.900e+03 -2.209e+03 -1.591e+03  1.574e+02
Anual_Salary                     1.546e-05  1.510e-05  1.581e-05  1.817e-07
                                t value Pr(&gt;|t|)    
(Intercept)                     -46.665  &lt; 2e-16 ***
sexmale                          -0.416 0.677332    
smokeryes                         3.726 0.000219 ***
age                              -2.268 0.023820 *  
bmi                              -1.428 0.153950    
Claim_Amount                     -0.601 0.548244    
past_consultations                0.767 0.443772    
num_of_steps                     46.586  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.075  &lt; 2e-16 ***
Anual_Salary                     85.090  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 795.8 on 452 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic:  8345 on 9 and 452 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Note que el porcentaje de varianza explicada aumentó de 99.1% a <strong>99.4%</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1091.864</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(mod_com_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 795.7768</code></pre>
</div>
</div>
<p>Asimismo, resaltamos que el <strong>residuo promedio es menor</strong> en el modelo tras remover puntos aberrantes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  mod_com_2<span class="sc">$</span>fitted.values,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  obs_sin_aber<span class="sc">$</span>charges,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"Estimados"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"Observados"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  mod_com_2<span class="sc">$</span>fitted.values,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  mod_com_2<span class="sc">$</span>residuals, </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"estimados"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"residuos"</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(mod_com_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>


data:  
= 167742048, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El p-valor asociado al test de homocedasticidad prácticamente no ha cambiado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>qq_completo_2 <span class="ot">&lt;-</span> <span class="fu">qqnorm</span>(mod_com_2<span class="sc">$</span>residuals)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mod_com_2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mod_com_2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mod_com_2$residuals
W = 0.99316, p-value = 0.03396</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">rstandard</span>(mod_com_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rstandard(mod_com_2)
W = 0.9933, p-value = 0.0379</code></pre>
</div>
</div>
<p>Por otro lado, el p-valor asociado al Test de Shapiro <strong>aumentó significativamente</strong>, de <span class="math inline">\(1.01*10^{-5}\)</span> a <span class="math inline">\(0.0379\)</span>. Este último valor es cercano a 0.05, aunque aún menor, por lo cual se sigue evidenciando la <strong>no normalidad</strong> de los residuos tras haber removido aquellos puntos aberrantes.</p>
<p>En base a estas comparaciones, el modelo tras haber removido los puntos aberrantes resulta <strong>mejor</strong> que el modelo inicialmente construido.</p>
</section>
<section id="selección-reducida-de-covariables" class="level3">
<h3 class="anchored" data-anchor-id="selección-reducida-de-covariables">Selección reducida de covariables</h3>
<p>Calculamos las correlaciones parciales para estas observaciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>covariables_numericas<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"age"</span>,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"bmi"</span>,</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Claim_Amount"</span>,</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"past_consultations"</span>,</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"num_of_steps"</span>,</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Number_of_past_hospitalizations"</span>,</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Anual_Salary"</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>d.cor<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">cor</span>(obs_sin_aber[, covariables_numericas<span class="fl">.2</span>])</span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>d.inv<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">solve</span>(d.cor<span class="fl">.2</span>)</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>d.corm<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1-1</span><span class="sc">/</span><span class="fu">diag</span>(d.inv<span class="fl">.2</span>))</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a>pd<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">length</span>(d.corm<span class="fl">.2</span>)  </span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>d.part<span class="fl">.2</span> <span class="ot">&lt;-</span> d.inv<span class="fl">.2</span></span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>pd<span class="fl">.2</span>) {</span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>)) {</span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a>    d.part<span class="fl">.2</span>[i,j] <span class="ot">&lt;-</span> <span class="sc">-</span>d.inv<span class="fl">.2</span>[i,j]<span class="sc">/</span><span class="fu">sqrt</span>(d.inv<span class="fl">.2</span>[i,i]<span class="sc">*</span>d.inv<span class="fl">.2</span>[j,j])</span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a>  d.part<span class="fl">.2</span>[i,i] <span class="ot">&lt;-</span> d.corm<span class="fl">.2</span>[i]</span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a>  d.part<span class="fl">.2</span>[<span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>),i] <span class="ot">&lt;-</span> d.part<span class="fl">.2</span>[i,<span class="dv">1</span><span class="sc">:</span>(i<span class="dv">-1</span>)]  </span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb69-26"><a href="#cb69-26" aria-hidden="true" tabindex="-1"></a>d.part<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         age         bmi Claim_Amount
age                              0.665243871  0.16416635  -0.07721888
bmi                              0.164166348  0.28642055  -0.04976349
Claim_Amount                    -0.077218876 -0.04976349   0.39336416
past_consultations               0.013448272  0.03776371   0.02053137
num_of_steps                     0.583992833 -0.11066826   0.06308460
Number_of_past_hospitalizations  0.006854609  0.06287529   0.07840750
Anual_Salary                    -0.461124002  0.15756448   0.10218653
                                past_consultations num_of_steps
age                                     0.01344827    0.5839928
bmi                                     0.03776371   -0.1106683
Claim_Amount                            0.02053137    0.0630846
past_consultations                      0.54647920    0.1470056
num_of_steps                            0.14700565    0.8882175
Number_of_past_hospitalizations        -0.03927175    0.4190512
Anual_Salary                            0.21686281    0.4624652
                                Number_of_past_hospitalizations Anual_Salary
age                                                 0.006854609   -0.4611240
bmi                                                 0.062875288    0.1575645
Claim_Amount                                        0.078407497    0.1021865
past_consultations                                 -0.039271754    0.2168628
num_of_steps                                        0.419051171    0.4624652
Number_of_past_hospitalizations                     0.834430684    0.3550532
Anual_Salary                                        0.355053223    0.8544968</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>vals_diag<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">diag</span>(d.part<span class="fl">.2</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>max_col_indices<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">apply</span>(d.part<span class="fl">.2</span>, <span class="dv">1</span>, which.max)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>idx_ordenados<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">order</span>(vals_diag<span class="fl">.2</span>, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>ordenados_vals_diag<span class="fl">.2</span> <span class="ot">&lt;-</span> vals_diag<span class="fl">.2</span>[idx_ordenados<span class="fl">.2</span>]</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">correlacion_parcial =</span> ordenados_vals_diag<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                correlacion_parcial
num_of_steps                              0.8882175
Anual_Salary                              0.8544968
Number_of_past_hospitalizations           0.8344307
age                                       0.6652439
past_consultations                        0.5464792
Claim_Amount                              0.3933642
bmi                                       0.2864205</code></pre>
</div>
</div>
<p>Note que aún existen covariables con correlación parcial elevada (<code>num_of_steps</code>, <code>Anual_Salary</code> y <code>Number_of_past_hospitalizations</code>), mayor que 0.8; pero ya no existe covariable con correlación parcial mayor a <span class="math inline">\(0.9\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Sin embargo, los valores pequeños en valor absoluto para correlación parcial entre par de covariables implica que existe <strong>poca multicolinealidad</strong> entre las covariables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>modelo_nulo <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> <span class="dv">1</span>, obs_sin_aber)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>modelo_completo<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(charges <span class="sc">~</span> ., obs_sin_aber)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>modelo_forward <span class="ot">&lt;-</span> <span class="fu">step</span>(</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  modelo_nulo,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">scope =</span> <span class="fu">list</span>(</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> modelo_nulo,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> modelo_completo<span class="fl">.2</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">"forward"</span>,</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace =</span> <span class="dv">0</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>modelo_backward <span class="ot">&lt;-</span> <span class="fu">step</span>(</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>  modelo_completo<span class="fl">.2</span>,</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">scope =</span> <span class="fu">list</span>(</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> modelo_nulo,</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> modelo_completo<span class="fl">.2</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">"backward"</span>,</span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace =</span> <span class="dv">0</span></span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a>modelo_both <span class="ot">&lt;-</span> <span class="fu">step</span>(</span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>  modelo_nulo,</span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">scope =</span> <span class="fu">list</span>(</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> modelo_nulo,</span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> modelo_completo<span class="fl">.2</span></span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">"both"</span>,</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace =</span> <span class="dv">0</span></span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_forward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ Anual_Salary + num_of_steps + Number_of_past_hospitalizations + 
    smoker + age + bmi, data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2281.32  -580.54   -16.49   544.60  2573.51 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.036e+04 -4.204e+04 -3.868e+04  8.553e+02
Anual_Salary                     1.547e-05  1.512e-05  1.582e-05  1.774e-07
num_of_steps                     5.532e-02  5.301e-02  5.762e-02  1.173e-03
Number_of_past_hospitalizations -1.909e+03 -2.216e+03 -1.602e+03  1.561e+02
smokeryes                        8.004e+02  3.744e+02  1.226e+03  2.168e+02
age                             -1.006e+01 -1.880e+01 -1.334e+00  4.443e+00
bmi                             -9.569e+00 -2.292e+01  3.777e+00  6.792e+00
                                t value Pr(&gt;|t|)    
(Intercept)                     -47.182  &lt; 2e-16 ***
Anual_Salary                     87.232  &lt; 2e-16 ***
num_of_steps                     47.146  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.227  &lt; 2e-16 ***
smokeryes                         3.692 0.000249 ***
age                              -2.265 0.023956 *  
bmi                              -1.409 0.159512    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 794 on 455 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic: 1.257e+04 on 6 and 455 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_backward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + age + bmi + num_of_steps + Number_of_past_hospitalizations + 
    Anual_Salary, data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2281.32  -580.54   -16.49   544.60  2573.51 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.036e+04 -4.204e+04 -3.868e+04  8.553e+02
smokeryes                        8.004e+02  3.744e+02  1.226e+03  2.168e+02
age                             -1.006e+01 -1.880e+01 -1.334e+00  4.443e+00
bmi                             -9.569e+00 -2.292e+01  3.777e+00  6.792e+00
num_of_steps                     5.532e-02  5.301e-02  5.762e-02  1.173e-03
Number_of_past_hospitalizations -1.909e+03 -2.216e+03 -1.602e+03  1.561e+02
Anual_Salary                     1.547e-05  1.512e-05  1.582e-05  1.774e-07
                                t value Pr(&gt;|t|)    
(Intercept)                     -47.182  &lt; 2e-16 ***
smokeryes                         3.692 0.000249 ***
age                              -2.265 0.023956 *  
bmi                              -1.409 0.159512    
num_of_steps                     47.146  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.227  &lt; 2e-16 ***
Anual_Salary                     87.232  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 794 on 455 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic: 1.257e+04 on 6 and 455 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ Anual_Salary + num_of_steps + Number_of_past_hospitalizations + 
    smoker + age + bmi, data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2281.32  -580.54   -16.49   544.60  2573.51 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.036e+04 -4.204e+04 -3.868e+04  8.553e+02
Anual_Salary                     1.547e-05  1.512e-05  1.582e-05  1.774e-07
num_of_steps                     5.532e-02  5.301e-02  5.762e-02  1.173e-03
Number_of_past_hospitalizations -1.909e+03 -2.216e+03 -1.602e+03  1.561e+02
smokeryes                        8.004e+02  3.744e+02  1.226e+03  2.168e+02
age                             -1.006e+01 -1.880e+01 -1.334e+00  4.443e+00
bmi                             -9.569e+00 -2.292e+01  3.777e+00  6.792e+00
                                t value Pr(&gt;|t|)    
(Intercept)                     -47.182  &lt; 2e-16 ***
Anual_Salary                     87.232  &lt; 2e-16 ***
num_of_steps                     47.146  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.227  &lt; 2e-16 ***
smokeryes                         3.692 0.000249 ***
age                              -2.265 0.023956 *  
bmi                              -1.409 0.159512    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 794 on 455 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic: 1.257e+04 on 6 and 455 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(modelo_forward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 794.0415</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(modelo_backward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 794.0415</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 794.0415</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1091.864</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_rse</span>(mod_com_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 795.7768</code></pre>
</div>
</div>
</section>
<section id="modelo-final" class="level3">
<h3 class="anchored" data-anchor-id="modelo-final">Modelo final</h3>
<p>Comparando las covariables finales de los tres últimos modelos creados, además de sus coeficientes respectivos, note que se trata de un único modelo.</p>
<p>Asimimo, aquel modelo presenta un <span class="math inline">\(R^2\)</span> elevado, similar al del previo mejor modelo, también con un valor aproximado a 99.4%.</p>
<p>No obstante, recalcamos que el nuevo modelo presenta un <strong>residuo promedio menor</strong> que el del mejor modelo que habíamos construído hasta ahora.</p>
<p>En ese sentido, el mejor modelo que planteamos es <code>modelo_both</code>. Este presenta como covariables a <code>age</code>, <code>Anual_Salary</code>, <code>bmi</code>, <code>smoker</code>, <code>num_of_steps</code> y <code>Number_of_past_hospitalizations</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>modelo_both</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ Anual_Salary + num_of_steps + Number_of_past_hospitalizations + 
    smoker + age + bmi, data = obs_sin_aber)

Coefficients:
                    (Intercept)                     Anual_Salary  
                     -4.036e+04                        1.547e-05  
                   num_of_steps  Number_of_past_hospitalizations  
                      5.532e-02                       -1.909e+03  
                      smokeryes                              age  
                      8.004e+02                       -1.006e+01  
                            bmi  
                     -9.569e+00  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  modelo_both<span class="sc">$</span>fitted.values,</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  obs_sin_aber<span class="sc">$</span>charges,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"Estimados"</span>,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"Observados"</span>,</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  modelo_both<span class="sc">$</span>fitted.values,</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  modelo_both<span class="sc">$</span>residuals, </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span><span class="st">"estimados"</span>,</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab=</span><span class="st">"residuos"</span>,</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch=</span><span class="dv">20</span>,</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex=</span><span class="fl">0.5</span></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Prueba de homocedasticidad</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>


data:  
= 167917219, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Prueba de normalidad de los errores</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>qq_completo_3 <span class="ot">&lt;-</span> <span class="fu">qqnorm</span>(modelo_both<span class="sc">$</span>residuals)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(modelo_both<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(modelo_both<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  modelo_both$residuals
W = 0.99308, p-value = 0.03182</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">rstandard</span>(modelo_both))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rstandard(modelo_both)
W = 0.99322, p-value = 0.03554</code></pre>
</div>
</div>
<p>Para este modelo también se concluye que no se cumple la homocedasticidad y que los residuos no presentan una distribución normal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: charges
                                 Df     Sum Sq    Mean Sq    F value    Pr(&gt;F)
Anual_Salary                      1 4.3922e+10 4.3922e+10 69661.4333 &lt; 2.2e-16
num_of_steps                      1 3.4856e+09 3.4856e+09  5528.3339 &lt; 2.2e-16
Number_of_past_hospitalizations   1 1.1417e+08 1.1417e+08   181.0800 &lt; 2.2e-16
smoker                            1 3.1743e+07 3.1743e+07    50.3452 4.973e-12
age                               1 3.1258e+06 3.1258e+06     4.9577   0.02646
bmi                               1 1.2518e+06 1.2518e+06     1.9853   0.15951
Residuals                       455 2.8688e+08 6.3050e+05                     
                                   
Anual_Salary                    ***
num_of_steps                    ***
Number_of_past_hospitalizations ***
smoker                          ***
age                             *  
bmi                                
Residuals                          
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extraer_estadistica_f</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
12571.36 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">obtener_p_valor_de_estadistica_f</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>value 
    0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extraer_info_t_student</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   t value      Pr(&gt;|t|) es_significativo
Anual_Salary                     87.232374 3.440579e-286             TRUE
num_of_steps                     47.145582 3.122331e-177             TRUE
Number_of_past_hospitalizations -12.227038  6.354538e-30             TRUE
smokeryes                         3.692271  2.492338e-04             TRUE
age                              -2.265428  2.395574e-02             TRUE
bmi                              -1.409021  1.595120e-01            FALSE</code></pre>
</div>
</div>
<p>A partir de estos dos últimos tests, se concluye que este modelo tiene sentido, pero que la covariable <code>bmi</code> no es significativa para ese modelo.</p>
<p>En base a que residuos de este modelo no satisfacen la hipótesis de homocedasticidad ni de distribución normal, no presentaremos los análisis de ANOVA tipo I, II ni III, por tratarse aquellas hipótesis de condiciones necesarias.</p>
</section>
</section>
<section id="discusión" class="level2">
<h2 class="anchored" data-anchor-id="discusión">Discusión</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_completo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ ., data = obs)

Residuals:
    Min      1Q  Median      3Q     Max 
-3574.8  -728.0  -121.6   631.4  3762.3 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.223e+04 -4.430e+04 -4.016e+04  1.055e+03
sexmale                          1.018e+02 -9.310e+01  2.967e+02  9.919e+01
smokeryes                        3.807e+02 -1.072e+02  8.686e+02  2.483e+02
age                             -2.649e+01 -3.670e+01 -1.628e+01  5.196e+00
bmi                             -1.680e+01 -3.465e+01  1.046e+00  9.083e+00
Claim_Amount                     2.238e-03 -4.649e-03  9.125e-03  3.505e-03
past_consultations               7.868e-01 -1.567e+01  1.725e+01  8.378e+00
num_of_steps                     5.771e-02  5.491e-02  6.051e-02  1.427e-03
Number_of_past_hospitalizations -1.022e+03 -1.405e+03 -6.391e+02  1.950e+02
Anual_Salary                     1.451e-05  1.411e-05  1.490e-05  2.028e-07
                                t value Pr(&gt;|t|)    
(Intercept)                     -40.029  &lt; 2e-16 ***
sexmale                           1.026    0.305    
smokeryes                         1.533    0.126    
age                              -5.097 4.93e-07 ***
bmi                              -1.850    0.065 .  
Claim_Amount                      0.639    0.523    
past_consultations                0.094    0.925    
num_of_steps                     40.434  &lt; 2e-16 ***
Number_of_past_hospitalizations  -5.242 2.37e-07 ***
Anual_Salary                     71.542  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1092 on 490 degrees of freedom
Multiple R-squared:  0.991, Adjusted R-squared:  0.9908 
F-statistic:  5977 on 9 and 490 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(mod_com_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ ., data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2250.13  -580.13   -19.38   534.20  2564.82 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.026e+04 -4.196e+04 -3.857e+04  8.628e+02
sexmale                         -3.150e+01 -1.801e+02  1.172e+02  7.564e+01
smokeryes                        8.137e+02  3.846e+02  1.243e+03  2.183e+02
age                             -1.011e+01 -1.887e+01 -1.348e+00  4.457e+00
bmi                             -9.743e+00 -2.315e+01  3.664e+00  6.823e+00
Claim_Amount                    -1.612e-03 -6.884e-03  3.660e-03  2.683e-03
past_consultations               4.894e+00 -7.653e+00  1.744e+01  6.384e+00
num_of_steps                     5.521e-02  5.288e-02  5.754e-02  1.185e-03
Number_of_past_hospitalizations -1.900e+03 -2.209e+03 -1.591e+03  1.574e+02
Anual_Salary                     1.546e-05  1.510e-05  1.581e-05  1.817e-07
                                t value Pr(&gt;|t|)    
(Intercept)                     -46.665  &lt; 2e-16 ***
sexmale                          -0.416 0.677332    
smokeryes                         3.726 0.000219 ***
age                              -2.268 0.023820 *  
bmi                              -1.428 0.153950    
Claim_Amount                     -0.601 0.548244    
past_consultations                0.767 0.443772    
num_of_steps                     46.586  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.075  &lt; 2e-16 ***
Anual_Salary                     85.090  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 795.8 on 452 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic:  8345 on 9 and 452 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum.lm</span>(modelo_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ Anual_Salary + num_of_steps + Number_of_past_hospitalizations + 
    smoker + age + bmi, data = obs_sin_aber)

Residuals:
     Min       1Q   Median       3Q      Max 
-2281.32  -580.54   -16.49   544.60  2573.51 

Coefficients:
                                                2.5 %     97.5 % Std. Error
(Intercept)                     -4.036e+04 -4.204e+04 -3.868e+04  8.553e+02
Anual_Salary                     1.547e-05  1.512e-05  1.582e-05  1.774e-07
num_of_steps                     5.532e-02  5.301e-02  5.762e-02  1.173e-03
Number_of_past_hospitalizations -1.909e+03 -2.216e+03 -1.602e+03  1.561e+02
smokeryes                        8.004e+02  3.744e+02  1.226e+03  2.168e+02
age                             -1.006e+01 -1.880e+01 -1.334e+00  4.443e+00
bmi                             -9.569e+00 -2.292e+01  3.777e+00  6.792e+00
                                t value Pr(&gt;|t|)    
(Intercept)                     -47.182  &lt; 2e-16 ***
Anual_Salary                     87.232  &lt; 2e-16 ***
num_of_steps                     47.146  &lt; 2e-16 ***
Number_of_past_hospitalizations -12.227  &lt; 2e-16 ***
smokeryes                         3.692 0.000249 ***
age                              -2.265 0.023956 *  
bmi                              -1.409 0.159512    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 794 on 455 degrees of freedom
Multiple R-squared:  0.994, Adjusted R-squared:  0.9939 
F-statistic: 1.257e+04 on 6 and 455 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Note que el último modelo presentado cuenta con el mayor <span class="math inline">\(R^2\)</span> ajustado, 99.39%, entre los modelos expuestos. Este criterio refuerza su selección como modelo final para este proyecto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>modelo_both</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ Anual_Salary + num_of_steps + Number_of_past_hospitalizations + 
    smoker + age + bmi, data = obs_sin_aber)

Coefficients:
                    (Intercept)                     Anual_Salary  
                     -4.036e+04                        1.547e-05  
                   num_of_steps  Number_of_past_hospitalizations  
                      5.532e-02                       -1.909e+03  
                      smokeryes                              age  
                      8.004e+02                       -1.006e+01  
                            bmi  
                     -9.569e+00  </code></pre>
</div>
</div>
<p>Entre lo positivo de este estudio, recalcamos que el modelo final presenta un alto valor de <span class="math inline">\(R^2\)</span>. Sin embargo, el hecho que para todos los modelos que creamos se llegó a concluir no homocedasticidad y residuos con distribución no normal, parece sugerir que el modelo de regresión lineal posiblemente no sea el adecuado para estos datos.</p>
<p>En todo caso, resulta posible que un modelo lineal generalizado resulte más apropiado para el uso con estos datos, en particular debido a la no homocedasticidad encontrada.</p>
<p>Respecto al mejor modelo que presentamos, analicemos la relevancia de las covariables que consideró para su definición:</p>
<ul>
<li><code>age</code>: Predictor muy relevante con la variable respuesta, pues, como se mencionó en una sección previa, sucede que paciente de mayor edad suelen requerir más cuidados médicos, su salud está en mayor riesgo, por lo que se espera que la aseguradora cubra más el costo de un tratamiento médico. En efecto, tal es el caso, pues el coeficiente asociado a <code>age</code> en el modelo resulta negativo. Así, a mayor edad del paciente, se espera que pague menos (pues la aseguradora cubre mayor costo) por un tratamiento médico.</li>
<li><code>Anual_Salary</code>: En el caso de pacientes con alto ingreso anual, se espera que sus tratamientos médicos sean también de alto costo. Esto implica que la aseguradora cubra una <strong>menor proporción</strong> del costo médico, pues la cobertura ya resulta alta en base al precio total del procedimiento. Esta relación se hace evidente en el hecho que el coeficiente asociado a <code>Annual_Salary</code> es positivo; es decir, a mayor salario anual, menos costo cubre la aseguradora.</li>
<li><code>bmi</code>: La relación entre esta covariable y la variable por predecir es muy similar la relación de la edad y la variable por predecir. Por ello, el análisis el análogo, y, simplemente recalcamos que el modelo resalta lo esperado (en base al coeficiente negativo asociado a <code>bmi</code>), pues, a mayor índice de masa corporal (<code>bmi</code>), la aseguradora cubre más del costo, por lo cual el paciente paga menos.</li>
<li><code>smoker</code>: En el modelo, esta covariable categórica ha sido convertida en 0 y 1; considerando el caso 1 cuando el paciente es fumador. En ese sentido, el coeficiente positivo asociado a esta covariable indice que, si el paciente es fumador, entonces su precio a pagar por tratamiento médico es también mayor, pues la aseguradora cubre <strong>menos</strong> del costo del procedimiento médico.</li>
<li><code>num_of_steps</code>: Recordemos que esta covariable la interpretamos como un indicador del estado de salud del paciente. Es decir, un mayor valor de <code>num_of_steps</code> representa un mejor estado de salud, de actividad física, del paciente. En ese sentido, es coherente que aquella covariable presente un coeficiente positivo según el modelo. Esto pues, mientras más saludable sea una persona, su gasto por procedimiento médico será mayor; es decir, la aseguradora cubrirá una <strong>menor</strong> cantidad del costo del procedimiento.</li>
<li><code>Number_of_past_hospitalizations</code>: Esta covariable es posiblemente la que más relación se espera tenga con la variable por predecir. El coeficiente negativo asociada a esta covariable es coherente con el hecho que, a mayor número de hospitalizaciones pasadas, se espera que el seguro cubra una mayor parte del costo del procedimiento médico, por lo cual el gasto del paciente es <strong>menor</strong> por procedimiento médico.</li>
</ul>
<p>Como no existe una interpretación física, realista, al caso <code>bmi = 0</code>, no interpretaremos el intercepto asociado al modelo.</p>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">Conclusiones</h2>
<ol type="1">
<li><p><strong>Validación de hipótesis sobre correlaciones</strong>: Se confirmaron las hipótesis respecto al tipo de correlación (positiva o negativa) entre las covariables del modelo final y el precio por pagar por procedimiento médico.</p></li>
<li><p><strong>Capacidad predictiva del modelo</strong>: El último modelo presentado logró explicar el <strong>99.4%</strong> de la varianza en el costo para el paciente por procedimiento médico, demostrando así una capacidad predictiva alta. Este nivel de precisión sugiere que las variables seleccionadas capturan efectivamente los factores determinantes en la cobertura de seguros médicos.</p></li>
<li><p><strong>Variables más influyentes identificadas</strong>: El análisis reveló que las variables más significativas para predecir los costos cubiertos son: edad (<code>age</code>), salario anual (<code>Annual_Salary</code>), índice de masa corporal (<code>bmi</code>), hábito de fumar (<code>smoker</code>), número de pasos (<code>num_of_steps</code>), y número de hospitalizaciones previas (<code>Number_of_past_hospitalizations</code>). Estas variables representan factores demográficos, socioeconómicos y de estilo de vida que las aseguradoras consideran en sus decisiones de cobertura.</p></li>
<li><p><strong>Limitaciones metodológicas detectadas</strong>: A pesar del alto poder predictivo, el modelo no satisface supuestos importante para la regresión lineal, la homocedasticidad y la normalidad de los residuos. Estas limitaciones sugieren que un modelo lineal simple podría no ser la aproximación más adecuada para estos datos.</p></li>
<li><p><strong>Recomendación de modelos alternativos</strong>: Los hallazgos de heterocedasticidad y no normalidad de residuos indican que un <strong>modelo lineal generalizado (GLM)</strong> podría ser más apropiado para este tipo de datos. Estos enfoques alternativos podrían proporcionar estimaciones más confiables, además de intervalos de confianza más precisos.</p></li>
<li><p><strong>Necesidad de validación externa</strong>: Aunque el modelo muestra alta precisión en los datos analizados, se recomienda validar estos resultados con datos de diferentes poblaciones, sistemas de salud y contextos geográficos para confirmar su generalización. Recalcamos que no se especifica en la fuente online de estos datos, la proveniencia de las observaciones analizadas.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>